we_crea:
    resource: "@WeCreaBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:   ['%http_protocol%']

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes:   ['%http_protocol%']

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    schemes:   ['%http_protocol%']


