# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.basket:
        class:     WeCreaBundle\Service\Basket
        arguments: []

    favs:
        class: WeCreaBundle\Service\Favs
        arguments: []

    uploader:
        class: WeCreaBundle\Service\FileUploader
        arguments: ['%image_directory%']

    wecrea_user.registration:
        class: WeCreaBundle\EventListener\RegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    wecrea_user.changepassword:
        class: WeCreaBundle\EventListener\ChangePassWordListener
        arguments: [ '@router' ]
        tags:
            - { name: kernel.event_subscriber }