we_crea_admin_homepage:
    path: /
    defaults:

we_crea_admin_artist_list:
    path: /artists/
    defaults: {_controller: "WeCreaBundle:Admin:artistList"}

we_crea_admin_artist_work_creation:
    path: /artist/creation
    defaults: {_controller: "WeCreaBundle:Admin:newArtistWork"}

we_crea_admin_artist_profil_creation_ajax:
    path: /artistProfil
    defaults: {_controller: "WeCreaBundle:Admin:newArtistProfilAjax"}

we_crea_admin_artist_image_creation_ajax:
    path: /artistImage
    defaults: {_controller: "WeCreaBundle:Admin:newArtistImageAjax"}

we_crea_admin_delete_artist:
    path: /artist/delete/{id}
    defaults: {_controller: "WeCreaBundle:Admin:deleteArtist"}

we_crea_admin_delete_artist_image_ajax:
    path: /deleteArtistImage
    defaults: {_controller: "WeCreaBundle:Admin:deleteArtistImageAjax"}

we_crea_admin_work_caracteristics_creation_ajax:
    path: /workCaracteristics
    defaults: {_controller: "WeCreaBundle:Admin:newWorkCaracteristicsAjax"}

we_crea_admin_work_image_creation_ajax:
    path: /workImage
    defaults: {_controller: "WeCreaBundle:Admin:newWorkImageAjax"}

we_crea_admin_delete_work_image_ajax:
    path: /deleteWorkImage
    defaults: {_controller: "WeCreaBundle:Admin:deleteWorkImageAjax"}

we_crea_admin_delete_work_ajax:
    path: /deleteWork
    defaults: {_controller: "WeCreaBundle:Admin:deleteWorkAjax"}

we_crea_admin_artist_work_edition:
    path: /artist/edition/{id}
    defaults: {_controller: "WeCreaBundle:Admin:editArtistWork"}

we_crea_admin_edit_profile_ajax:
    path: /editProfile
    defaults: {_controller: "WeCreaBundle:Admin:editProfileAjax"}

we_crea_admin_edit_work_ajax:
    path: /editWork
    defaults: {_controller: "WeCreaBundle:Admin:editWorkAjax"}

we_crea_admin_carrousel_edition:
    path: /carrousel/edition
    defaults: {_controller: "WeCreaBundle:Admin:editCarrousel"}

we_crea_admin_image_carrousel:
    path: /carrousel/image
    defaults: {_controller: "WeCreaBundle:Admin:addImageCarrousel"}

we_crea_admin_add_carrousel:
    path: /carrousel/add
    defaults: {_controller: "WeCreaBundle:Admin:addCarrousel"}

we_crea_admin_delete_carrousel:
    path: /carrousel/delete
    defaults: {_controller: "WeCreaBundle:Admin:deleteCarrousel"}

we_crea_admin_actu:
    path: /actu
    defaults: {_controller: "WeCreaBundle:Admin:actu"}

we_crea_admin_actu_add:
    path: /actu/add
    defaults: {_controller: "WeCreaBundle:Admin:addActu"}
we_crea_admin_actu_delete:
    path: /actu/delete
    defaults: {_controller: "WeCreaBundle:Admin:deleteActu"}