we_crea_homepage:
    path:    /
    defaults: {_controller: "WeCreaBundle:User:index"}

we_crea_works:
    path: /works
    defaults: {_controller: "WeCreaBundle:User:worksShow"}

we_crea_work:
    path: /work/{id}
    defaults: {_controller: "WeCreaBundle:User:workShow"}
    requirements:
        id: \d+

we_crea_artists_list:
    path: /artists
    defaults: {_controller: "WeCreaBundle:User:artistsShow"}

we_crea_artist:
    path: /artist/{id}
    defaults: {_controller: "WeCreaBundle:User:artistShow"}
    requirements:
        id: \d+

we_crea_add_basket:
    path: /work/basket/add
    defaults: {_controller: "WeCreaBundle:User:addBasket"}
    methods: 'POST'