WeCreaBundle\Entity\Nature:
    type: entity
    table: null
    repositoryClass: WeCreaBundle\Repository\NatureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        fontColor:
            type: string
            length: 255


    oneToOne:
        images:
            targetEntity: WeCreaBundle\Entity\Images
            cascade: ['all']

    lifecycleCallbacks: {  }
