WeCreaBundle\Entity\Subscriber:
    type: entity
    table: null
    repositoryClass: WeCreaBundle\Repository\SubscriberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
            unique: true
        date:
            type: datetime
        token:
            type: string
            length: 255
    lifecycleCallbacks: {  }
