WeCreaBundle\Entity\Work:
    type: entity
    table: null
    repositoryClass: WeCreaBundle\Repository\WorkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        technic:
            type: string
            length: 255
        dimensions:
            type: string
            length: 255
        dimensions2:
            type: string
            length: 255
            nullable: true
        dimensions3:
            type: string
            length: 255
            nullable: true
        dimensions4:
            type: string
            length: 255
            nullable: true
        dimensions5:
            type: string
            length: 255
            nullable: true
        weight:
            type: string
            length: 255
        weight2:
            type: string
            length: 255
            nullable: true
        weight3:
            type: string
            length: 255
            nullable: true
        weight4:
            type: string
            length: 255
            nullable: true
        weight5:
            type: string
            length: 255
            nullable: true
        quantity:
            type: integer
        quantity2:
            type: integer
            nullable: true
        quantity3:
            type: integer
            nullable: true
        quantity4:
            type: integer
            nullable: true
        quantity5:
            type: integer
            nullable: true
        timelimit:
            type: string
            length: 255
        price:
            type: integer
        price2:
            type: integer
            nullable: true
        price3:
            type: integer
            nullable: true
        price4:
            type: integer
            nullable: true
        price5:
            type: integer
            nullable: true
    manyToOne:
        artist:
            targetEntity: WeCreaBundle\Entity\Artist
            inversedBy: works
        nature:
            targetEntity: WeCreaBundle\Entity\Nature

    manyToMany:
        images:
            targetEntity: WeCreaBundle\Entity\Images
            cascade: ['all']
